trainer:
  precision: 16-mixed
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: PhysionetMotorImagery
  max_epochs: -1
  limit_train_batches: 250
  limit_val_batches: 50
model:
  class_path: eegformer.models.Transformer
  init_args:
    model_dim: 160
    n_layer: 4
    n_head: 8
    hidden_layer_multiplier: 4
    learning_rate: 1e-3
    weight_decay: 0.05
    dropout: 0.2
    warmup_steps: 1000
    lr_decay_steps: 100000
    input_dim: 160
data:
  dataclass: eegformer.datasets.PhysionetMotorImagery
  dataset_kwargs:
    task: ALL
    root: ~/data
  preprocessing:
    epoch_length: 1
    epoch_overlap: 0
    low_pass: 60
    high_pass: 1
    n_jobs: -1
  batch_size: 4096
  num_workers: 24
  augmentations:
    class_path: eegformer.augmentations.Compose
    init_args:
      max_transforms: 4
      transforms:
        - class_path: eegformer.augmentations.GaussianNoiseSignal
        - class_path: eegformer.augmentations.GaussianNoiseChannelPos
        - class_path: eegformer.augmentations.RandomTimeShift
        - class_path: eegformer.augmentations.FourierNoise
        - class_path: eegformer.augmentations.RandomAmplitudeScaleShift
        - class_path: eegformer.augmentations.RandomPhase
        - class_path: eegformer.augmentations.ChannelDropout