trainer:
  precision: 16-mixed
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: PhysionetMotorImagery
  max_epochs: -1
model:
  class_path: eegformer.models.Transformer
  init_args:
    model_dim: 64
    n_layer: 4
    n_head: 4
    hidden_layer_multiplier: 4
    learning_rate: 5e-4
    weight_decay: 0.0
    dropout: 0.0
    warmup_steps: 1000
    lr_decay_steps: 50000
    input_dim: 320
data:
  class_path: eegformer.datasets.PhysionetMotorImagery
  init_args:
    task: ALL
    batch_size: 512
    num_workers: 20
    root: ~/data
    # augmentations:
    #   class_path: eegformer.augmentations.Compose
    #   init_args:
    #     max_transforms: 1
    #     transforms:
    #       - class_path: eegformer.augmentations.GaussianNoiseSignal
    #       - class_path: eegformer.augmentations.GaussianNoiseChannelPos
    #       - class_path: eegformer.augmentations.RandomTimeShift
    #       - class_path: eegformer.augmentations.FourierNoise
    #       - class_path: eegformer.augmentations.RandomAmplitudeScaleShift
    #       - class_path: eegformer.augmentations.RandomPhase